// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK8gexvuF9Wcm5LKPYDHLuG2DXt_xfsjE',
    appId: '1:339138797962:web:884b811ae5efc72d8ba873',
    messagingSenderId: '339138797962',
    projectId: 'momdoctor-3bc3b',
    authDomain: 'momdoctor-3bc3b.firebaseapp.com',
    storageBucket: 'momdoctor-3bc3b.firebasestorage.app',
    measurementId: 'G-Q9Z6JG7YHE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8ZYpTqGxw8imaipghBbTfxIj9nSCO0zQ',
    appId: '1:339138797962:android:11c4381bdf4dd65d8ba873',
    messagingSenderId: '339138797962',
    projectId: 'momdoctor-3bc3b',
    storageBucket: 'momdoctor-3bc3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjBX5U8kcxwLVYpk4kzwuXLP8U_KoOBMU',
    appId: '1:339138797962:ios:e6b8ba93ed6a46878ba873',
    messagingSenderId: '339138797962',
    projectId: 'momdoctor-3bc3b',
    storageBucket: 'momdoctor-3bc3b.firebasestorage.app',
    iosClientId: '339138797962-h4ste969ucv23fhaa4ii39bcgp996g4e.apps.googleusercontent.com',
    iosBundleId: 'com.example.babyCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDK8gexvuF9Wcm5LKPYDHLuG2DXt_xfsjE',
    appId: '1:339138797962:web:0d4d60976aef005a8ba873',
    messagingSenderId: '339138797962',
    projectId: 'momdoctor-3bc3b',
    authDomain: 'momdoctor-3bc3b.firebaseapp.com',
    storageBucket: 'momdoctor-3bc3b.firebasestorage.app',
    measurementId: 'G-CD8D0L6JDZ',
  );
}
